### ISSUE TITLE
ResourceGroupName ParameterBindingValidationException

### ISSUE THREAD

**Issue by rfcdejong** [carlosjdelgado/AzureStorageContainer#5]
2018-10-05T08:29:21.8010724Z System.Management.Automation.ParameterBindingValidationException: Cannot validate argument on parameter 'ResourceGroupName'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again. ---> System.Management.Automation.ValidationMetadataException: The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
2018-10-05T08:29:21.8010970Z    at System.Management.Automation.ValidateNotNullOrEmptyAttribute.Validate(Object arguments, EngineIntrinsics engineIntrinsics)
2018-10-05T08:29:21.8011087Z    at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
2018-10-05T08:29:21.8011224Z    --- End of inner exception stack trace ---
2018-10-05T08:29:21.8011302Z    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
2018-10-05T08:29:21.8013283Z    at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
2018-10-05T08:29:21.8013360Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2018-10-05T08:29:21.8013447Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2018-10-05T08:29:21.8013488Z 
2018-10-05T08:29:21.8013516Z 
2018-10-05T08:29:21.8061403Z ##[error]System.Management.Automation.ParentContainsErrorRecordException: Cannot validate argument on parameter 'ResourceGroupName'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
2018-10-05T08:29:21.8401348Z ##[error]PowerShell script completed with 1 errors.
2018-10-05T08:29:21.8414581Z ##[section]Finishing: Create blob container inside azure storage

**Comment by carlosjdelgado** [comment]
Can you give me more info? Hace you setted resource group parameter?

**Comment by rfcdejong** [comment]
I already deinstalled it, but there was no other field to fill in within the task that was used inside the pipeline.
